name: CI

on: [push]

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 24hr

  build:
    if: "!contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    name: build and run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Download dependencies
        run: |
          ./gradlew dependencies --stacktrace

      - name: Build debug - assembleDebug
        run: |
          ./gradlew assembleDebug --stacktrace

      - name: Test debug
        run: |
          ./gradlew :app:testDebug --stacktrace

      - name: Assemble Android Instrumentation Tests
        run: ./gradlew assembleDebugAndroidTest

      - name: Upload app APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Android Test APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug-androidTest
          path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk

